### ISSUE TITLE
Instructions to lift AArch64 /bin directory

### ISSUE THREAD

**Issue by perks** [lifting-bits/remill#150]
- [x] ADD_ASIMDSAME_ONLY `2`
 - [x] ADDV_ASIMDALL_ONLY `2`
 - [x] BIC_ASIMDSAME_ONLY `1`
 - [x] BICS_32_LOG_SHIFT `42`
 - [x] BICS_64_LOG_SHIFT `22`
 - [x] CCMN_32_CONDCMP_IMM `250`
 - [x] CCMN_64_CONDCMP_IMM `55`
 - [x] CMGT_ASIMDSAME_ONLY `1` **[untested]**
 - [x] DMB_BO_SYSTEM `39`  **[untested]**
 - [x] DUP_ASIMDINS_DR_R `3`
 - [x] FABS_D_FLOATDP1 `2`
 - [x] FCMP_DZ_FLOATCMP `11`
 - [x] FCVT_DS_FLOATDP1 `2`
 - [x] FCVT_SD_FLOATDP1 `1`
 - [x] FCVTZS_32D_FLOAT2INT `2`
 - [x] FCVTZS_64D_FLOAT2INT `7`
 - [x] FCVTZU_32D_FLOAT2INT `2`
 - [x] FCVTZU_32S_FLOAT2INT `2`
 - [x] FCVTZU_64D_FLOAT2INT `11`
 - [x] FMADD_D_FLOATDP3 `6`
 - [x] FMOV_D_FLOATDP1 `12`
 - [x] FMOV_S_FLOATDP1 `1`
 - [x] FNEG_D_FLOATDP1 `2`
 - [x] LD1_ASISDLSEP_I1_I1 `2`
- [x] LD1_ASISDLSEP_I2_I2
- [x] LD1_ASISDLSEP_I3_I3
- [x] LD1_ASISDLSEP_I4_I4
 - [x] LD1_ASISDLSE_R1_1V `3`
 - [x] LD1_ASISDLSE_R2_2V `34`
 - [x] LD2_ASISDLSEP_I2_I `1`
 - [x] LDPSW_64_LDSTPAIR_OFF `6`
 - [x] LDURSB_32_LDST_UNSCALED `5`
 - [x] LDURSH_32_LDST_UNSCALED `3`
 - [x] LDURSW_64_LDST_UNSCALED `2`
 - [x] LDXR_LR32_LDSTEXCL `29`
 - [x] LDXR_LR64_LDSTEXCL `4`
 - [x] MOVI_ASIMDIMM_D2_D `4` 
 - [x] MOVI_ASIMDIMM_L_SL `5` 
 - [x] MSR_SR_SYSTEM `15`
 - [x] MVNI_ASIMDIMM_L_SL `4` 
 - [x] NOT_ASIMDMISC_R `3` 
 - [x] REV16_32_DP_1SRC `85`
 - [x] REV_32_DP_1SRC `241`
 - [x] REV_64_DP_1SRC `87`
 - [x] SCVTF_D32_FLOAT2INT `3`
 - [x] SCVTF_D64_FLOAT2INT `22`
 - [x] SDIV_32_DP_2SRC `63`
 - [x] SDIV_64_DP_2SRC `94`
 - [x] SMAX_ASIMDSAME_ONLY `1` **[untested]**
 - [x] SMAXV_ASIMDALL_ONLY `1`
 - [x] STLXR_SR32_LDSTEXCL `1` 
 - [x] STLXR_SR64_LDSTEXCL `4` 
 - [x] STP_D_LDSTPAIR_OFF `26`
 - [x] STRH_32_LDST_IMMPOST `59`
 - [x] STRH_32_LDST_IMMPRE `6`
 - [x] STRH_32_LDST_REGOFF `140`
 - [x] STR_Q_LDST_IMMPRE `4`
 - [x] STR_Q_LDST_REGOFF `27`

**Comment by mike-myers-tob** [comment]
What do the numbers to the right of each instruction mnemonic in the above list signify?

**Comment by pgoodman** [comment]
Number of appearances across binaries in the `/bin` directory.

**Comment by pgoodman** [comment]
- [ ] `FCVTZS_32S_FLOAT2INT`
 - [ ] `MRS_RS_SYSTEM_FPCR`
 - [ ] `MRS_RS_SYSTEM_TPIDR_EL0`
 - [ ] `BSL_ASIMDSAME_ONLY`
 - [ ] `EON_64_LOG_SHIFT`
 - [ ] `FCMP_D_FLOATCMP`
 - [ ] `FCMP_S_FLOATCMP`
 - [ ] `FCMP_SZ_FLOATCMP`
 - [ ] `LDAXR_LR32_LDSTEXCL`
 - [ ] `LDAXR_LR64_LDSTEXCL`
 - [ ] `LDPSW_64_LDSTPAIR_OFF`
 - [ ] `LDURSW_64_LDST_UNSCALED`
 - [ ] `MOVI_ASIMDIMM_D2_D`
 - [ ] `NOP_HI_SYSTEM`
 - [ ] `ST1_ASISDLSE_R2_2V`
 - [ ] `STLR_SL32_LDSTEXCL`
 - [ ] `STP_Q_LDSTPAIR_POST`
 - [ ] `STXR_SR32_LDSTEXCL`
 - [ ] `STXR_SR64_LDSTEXCL`
 - [ ] `SYS_CR_SYSTEM`
 - [ ] `USHR_ASISDSHF_R`

**Comment by pgoodman** [comment]
- [ ] `EXT_ASIMDEXT_ONLY`
 - [ ] `INS_ASIMDINS_IR_R`
 - [ ] `LD4_ASISDLSE_R4`
 - [ ] `ST1_ASISDLSE_R2_2V`
 - [ ] `XTN_ASIMDMISC_N`
 - [ ] `USHLL_ASIMDSHF_L`
 - [ ] `FCMP_D_FLOATCMP`

**Comment by artemdinaburg** [comment]
Closing since this is quite dated
