### ISSUE TITLE
Model certain instructions' memory operand alignment, cache behavior

### ISSUE THREAD

**Issue by mike-myers-tob** [lifting-bits/remill#174]
Certain instructions (in X86 at least, and likely other architectures) check for memory operand alignment, and `SIGSEGV` if the operand is not aligned to a particular boundary – 16-byte alignment (with 128-bit operands) or 32-byte alignment (with 256-bit operands). The reason for this is that the processor requires two memory accesses to make an unaligned memory access; aligned accesses require only one memory access. A word or doubleword operand that crosses a 4-byte boundary or a quadword operand that crosses an 8-byte boundary is considered unaligned and requires two separate memory bus cycles for access. The Remill semantics for such instructions are not modeling memory operand alignment requirements, and will never throw a CPU exception if the memory operand is misaligned. 

Similarly, the X86 "non-temporal move instructions" (`MOVNTxxx`), when executed natively, write data from a register out to memory while bypassing the CPU caches. We do not model this behavior. All `MOVNT` instructions alias to the equivalent normal `MOV` instructions.

Since I think the choice not to model these aspects of memory was a design decision and this is a `wontfix` issue, maybe the solution is to add these notes to the Remill documentation.

**Comment by artemdinaburg** [comment]
Just commenting to say its probably a `wontfix`, but maybe something will come up where we need to decide differently. 

Typically, we have not modeled various exceptions that can happen during instruction execution. If we start, the semantics for many simple instructions may get needlessly slow and complicated.
