### ISSUE TITLE
Enabling tests on Windows

### ISSUE THREAD

**Issue by alessandrogario** [lifting-bits/remill#253]
I have been looking into this and after some debugging I found the following issues:

1. **gtest** needs to be manually recompiled with [/MD](https://docs.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library) to avoid linking issues
2. CMake: When using the Visual Studio generator, the ASM language option in the `project` directive does nothing; we need to use ASM_MASM instead
3. CMake: The **.S** extension is not recognized when using the Visual Studio generator; we need to rename **Tests.S** to **Tests.asm**. I have tried to force the language to `ASM_MASM` using `set_source_files_properties("Test.S" PROPERTIES LANGUAGE ASM_MASM)` but it didn't work. The remaining **.S** files are included so there is no need to rename those as well.
4. The syntax used by the **.S** files is not compatible with MASM

It is easy to fix the first three, but the fourth is currently the biggest problem

**Comment by alessandrogario** [comment]
I was thinking about just building that into an .obj and then link it with the rest (maybe using CMake OBJECT libraries?)

**Comment by pgoodman** [comment]
Sure?

**Comment by alessandrogario** [comment]
Turns out that object libraries don't really play nice when using anything that is not makefile (or ninja) based. I have been trying to compile things directly by calling `clang++.exe` with several `add_custom_command` directives but I'm not having much luck:

```
C:/TrailOfBits/libraries/llvm/bin/clang++.exe -DLLVM_BUILD_GLOBAL_ISEL \
  -D_DEBUG_POINTER_IMPL= -D_CRT_SECURE_NO_DEPRECATE \
  -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE \
  -D_CRT_NONSTDC_NO_WARNINGS -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS \
  -DUNICODE -D_UNICODE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS \
  -D__STDC_LIMIT_MACROS -DREMILL_INSTALL_SEMANTICS_DIR="C://remill/5.0/semantics//" \
  -DREMILL_BUILD_SEMANTICS_DIR_X86="C:/Projects/remill_build/remill/Arch/X86/Runtime/" \
  -DREMILL_BUILD_SEMANTICS_DIR_AARCH64="C:/Projects/remill_build/remill/Arch/AArch64/Runtime/" \
  -DIN_TEST_GENERATOR -IC:/TrailOfBits/libraries/llvm/include \
  -IC:/TrailOfBits/libraries/gflags/include \
  -IC:/TrailOfBits/libraries/glog/include -IC:\TrailOfBits\libraries/xed/include \
  -IC:/Projects/remill -IC:\TrailOfBits\libraries/googletest/include -lLLVMCore \
  -lLLVMSupport -lLLVMAnalysis -lLLVMipo -lLLVMIRReader -lLLVMBitReader \
  -lLLVMBitWriter -lLLVMTransformUtils -lLLVMScalarOpts -lLLVMLTO \
  -lC:\TrailOfBits\libraries/xed/lib/xed.lib \
  -lC:\TrailOfBits\libraries/xed/lib/xed-ild.lib \
  -lglog -lgflags -lKernel32 -lC:\TrailOfBits\libraries/googletest/lib/gtest.lib \
  -IC:/Projects/remill -DADDRESS_SIZE_BITS=32 -DHAS_FEATURE_AVX=0 -DHAS_FEATURE_AVX512=0 \
  -DGTEST_HAS_RTTI=0 -DGTEST_HAS_TR1_TUPLE=0 C:/Projects/remill/tests/X86/Lift.cpp \
  C:/Projects/remill/tests/X86/Tests.S
```

Output:

> C:/Projects/remill/tests/X86/Tests.S:314:14: error: expected identifier in directive
>     .section "__x86_test_table", "a"
>              ^
> C:/Projects/remill\\tests/X86/DATAXFER/MOV.S:32:66: error: expected identifier in directive
> .text ; .align 16 ; .globl MOVr16r16_2 ; MOVr16r16_2: ; .section "__x86_test_table", "a" ; .balign 128 ; 1: .quad 3f ; .quad 6f ; .quad 2f ; .quad 4f ; .quad 5f ; .quad 2 ; .rodata ; 2: .asciz "MOVr16r16_2" ; .text ; 3: .cfi_startproc ;
>                                                                  ^
> C:/Projects/remill\\tests/X86/DATAXFER/MOV.S:32:174: error: unknown directive
> .text ; .align 16 ; .globl MOVr16r16_2 ; MOVr16r16_2: ; .section "__x86_test_table", "a" ; .balign 128 ; 1: .quad 3f ; .quad 6f ; .quad 2f ; .quad 4f ; .quad 5f ; .quad 2 ; .rodata ; 2: .asciz "MOVr16r16_2" ; .text ; 3: .cfi_startproc ;
>                                                                                                                                                                              ^
> C:/Projects/remill\\tests/X86/DATAXFER/MOV.S:40:28: error: expected identifier in directive
> 6: .cfi_endproc ; .section "__x86_test_table", "a" ; .quad 0 ; .text ; ud2 ;
>                            ^
> C:/Projects/remill\\tests/X86/DATAXFER/MOV.S:42:66: error: expected identifier in directive
> .text ; .align 16 ; .globl MOVr16i15_1 ; MOVr16i15_1: ; .section "__x86_test_table", "a" ; .balign 128 ; 1: .quad 3f ; .quad 6f ; .quad 2f ; .quad 4f ; .quad 5f ; .quad 1 ; .rodata ; 2: .asciz "MOVr16i15_1" ; .text ; 3: .cfi_startproc ;
>                                                                  ^
> C:/Projects/remill\\tests/X86/DATAXFER/MOV.S:42:174: error: unknown directive
> .text ; .align 16 ; .globl MOVr16i15_1 ; MOVr16i15_1: ; .section "__x86_test_table", "a" ; .balign 128 ; 1: .quad 3f ; .quad 6f ; .quad 2f ; .quad 4f ; .quad 5f ; .quad 1 ; .rodata ; 2: .asciz "MOVr16i15_1" ; .text ; 3: .cfi_startproc ;
>                                                                                                                                                                              ^
> C:/Projects/remill\\tests/X86/DATAXFER/MOV.S:46:28: error: expected identifier in directive
> 6: .cfi_endproc ; .section "__x86_test_table", "a" ; .quad 0 ; .text ; ud2 ;
>                            ^
> C:/Projects/remill\\tests/X86/DATAXFER/MOV.S:48:66: error: expected identifier in directive
> .text ; .align 16 ; .globl MOVr32r32_2 ; MOVr32r32_2: ; .section "__x86_test_table", "a" ; .balign 128 ; 1: .quad 3f ; .quad 6f ; .quad 2f ; .quad 4f ; .quad 5f ; .quad 2 ; .rodata ; 2: .asciz "MOVr32r32_2" ; .text ; 3: .cfi_startproc ;
>                                                                  ^
> C:/Projects/remill\\tests/X86/DATAXFER/MOV.S:48:174: error: unknown directive
> .text ; .align 16 ; .globl MOVr32r32_2 ; MOVr32r32_2: ; .section "__x86_test_table", "a" ; .balign 128 ; 1: .quad 3f ; .quad 6f ; .quad 2f ; .quad 4f ; .quad 5f ; .quad 2 ; .rodata ; 2: .asciz "MOVr32r32_2" ; .text ; 3: .cfi_startproc ;
>                                                                                                                                                                              ^
> C:/Projects/remill\\tests/X86/DATAXFER/MOV.S:57:28: error: expected identifier in directive
> 6: .cfi_endproc ; .section "__x86_test_table", "a" ; .quad 0 ; .text ; ud2 ;
>                            ^
> C:/Projects/remill\\tests/X86/DATAXFER/MOV.S:59:66: error: expected identifier in directive
> .text ; .align 16 ; .globl MOVr32i32_1 ; MOVr32i32_1: ; .section "__x86_test_table", "a" ; .balign 128 ; 1: .quad 3f ; .quad 6f ; .quad 2f ; .quad 4f ; .quad 5f ; .quad 1 ; .rodata ; 2: .asciz "MOVr32i32_1" ; .text ; 3: .cfi_startproc ;
>                                                                  ^
> C:/Projects/remill\\tests/X86/DATAXFER/MOV.S:59:174: error: unknown directive
> .text ; .align 16 ; .globl MOVr32i32_1 ; MOVr32i32_1: ; .section "__x86_test_table", "a" ; .balign 128 ; 1: .quad 3f ; .quad 6f ; .quad 2f ; .quad 4f ; .quad 5f ; .quad 1 ; .rodata ; 2: .asciz "MOVr32i32_1" ; .text ; 3: .cfi_startproc ;
>                                                                                                                                                                              ^
> C:/Projects/remill\\tests/X86/DATAXFER/MOV.S:63:28: error: expected identifier in directive
> 6: .cfi_endproc ; .section "__x86_test_table", "a" ; .quad 0 ; .text ; ud2 ;
> ...
> ...
