### ISSUE TITLE
Update build.sh to fetch and build cxx-common when a package is not available

### ISSUE THREAD

**Issue by pgoodman** [lifting-bits/remill#282]

**Comment by ianklatzco** [comment]
What exactly do you mean by "when a package is not available"?

It looks like cxx-common is already downloaded, but not built. `DownloadCxxCommon` is called by `DownloadLibraries` (so long as `${BUILD_DIR}/libraries ` exists.)

https://github.com/trailofbits/remill/blob/4570985647c2bb0d9cc8f8c30aedc0356708f1b8/scripts/build.sh#L301

**Comment by pgoodman** [comment]
Well if you experiment with enough versions/OS mixes then you'll discover that some files don't exist on s3. This issue exists to suggest that if the download fails, then we should clone cxx-common and then run pkgman.py to build the requested packages.

**Comment by yksee** [comment]
For example, I tried to use LLVM version 9. It tried to download libraries-llvm90-ubuntu1804-amd64.tar.gz, which is missing on s3.

**Comment by pgoodman** [comment]
You can follow these instructions:
https://gist.github.com/pgoodman/0882459dc2ecff0e674b79815e9301ff

**Comment by pgoodman** [comment]
You might find the build you want here, as well:
https://github.com/trailofbits/cxx-common/actions/runs/42577741

**Comment by pgoodman** [comment]
Closing as we pull the relevant things from github
