### ISSUE TITLE
Tricky lifting

### ISSUE THREAD

**Issue by tathanhdinh** [lifting-bits/remill#320]
I'm currently trying to add some more vectorized instructions into remill (`rcpps`, `sqrtps` and alike). A ["standard"](https://github.com/trailofbits/remill/pull/307) method for such a case is to divide the operation into sub-operators: each for a packed 32-bit floating point; then implement the semantics function for the operation. For example, with `rcpps` we should implement `1/x` for 32-bit float sub-operation. 

But I found that these instructions have been already implemented by `x86intrin`, that leads me to a simple and dirty implementation for `rcpps`:

```c++
namespace
{

#include <x86intrin.h>

template <typename D, typename S1>
DEF_SEM(RCPPS_RR, D dst, S1 src1) {
  auto src1_val128 = *reinterpret_cast<const __m128*>(src1.val);
  auto dst_ref128 = reinterpret_cast<__m128*>(dst.val_ref);
  *dst_ref128 = _mm_rcp_ps(src1_val128);

  return memory;
}

template <typename D, typename S1>
DEF_SEM(RCPPS_RM, D dst, S1 src1) {
  auto src1_val128 = reinterpret_cast<__m128>(__remill_read_memory_128(memory, src1.addr));
  auto dst_ref128 = reinterpret_cast<__m128*>(dst.val_ref);
  *dst_ref128 = _mm_rcp_ps(src1_val128);

  return memory;
}

DEF_ISEL(RCPPS_XMMps_XMMps) = RCPPS_RR<V128W, V128>;
DEF_ISEL(RCPPS_XMMps_MEMps) = RCPPS_RM<V128W, MV128>;

} // namespace
```

which passes the newly added tests. 

More concretely the lifting tool gives the following result for `rcpps xmm0, xmm1`:

```llvm
; Function Attrs: noinline nounwind
define dso_local %struct.Memory* @sub_0(%struct.State* noalias dereferenceable(3280), i64, %struct.Memory* noalias) local_unnamed_addr #0 {
  %4 = getelementptr inbounds %struct.State, %struct.State* %0, i64 0, i32 6, i32 33, i32 0, i32 0
  %5 = getelementptr inbounds %struct.State, %struct.State* %0, i64 0, i32 1
  %6 = getelementptr inbounds %struct.State, %struct.State* %0, i64 0, i32 1, i64 1
  %7 = add i64 %1, 3
  store i64 %7, i64* %4, align 8
  %8 = bitcast %union.VectorReg* %6 to <4 x float>*
  %9 = load <4 x float>, <4 x float>* %8, align 16
  %10 = bitcast [32 x %union.VectorReg]* %5 to <4 x float>*
  %11 = tail call <4 x float> @llvm.x86.sse.rcp.ps(<4 x float> %9) #3
  store <4 x float> %11, <4 x float>* %10, align 16
  %12 = tail call %struct.Memory* @__remill_missing_block(%struct.State* nonnull %0, i64 %7, %struct.Memory* %2)
  ret %struct.Memory* %12
}

; Function Attrs: nounwind readnone
declare <4 x float> @llvm.x86.sse.rcp.ps(<4 x float>) #1
```

This is "tricky" because that's `x86intrin` which really does the work. I still wonder if such an implementation would be accepted, or it falls into a anti-goal of remill (as discussed in a [previous](https://github.com/trailofbits/remill/pull/307) PR).

Many thanks for any comment.

**Comment by pgoodman** [comment]
What happens if you implement it in the "long form" way, i.e. manually, but modify the `MAKE_VECTOR` macro in remill/Arch/Runtime/Types.h into a vector type, instead of an array type, as is shown below (and associated enabling of vectorization in the CMakeLists.txt and optimizing functions).

```c++
#define MAKE_VECTOR(base_type, prefix, nelems, vec_size_bits, width_bytes) \
    struct prefix ## v ## nelems ## _t final { \
      using vec_type = base_type __attribute__((vector_size(width_bytes)));
      vec_type elems ; \
    } __attribute__((packed)); \
    \
    static_assert(width_bytes == sizeof(prefix ## v ## nelems ## _t), \
        "Invalid definition of `" #prefix "v" #nelems "`."); \
    \
    static_assert((width_bytes * 8) == vec_size_bits, \
        "Invalid definition of `" #prefix "v" #nelems "`."); \
    \
    template <> \
    struct VectorType<prefix ## v ## nelems ## _t> { \
      enum : size_t { \
        kNumElems = nelems \
      }; \
      typedef base_type BT; \
      typedef base_type BaseType; \
      typedef vec ## vec_size_bits ## _t T; \
      typedef vec ## vec_size_bits ## _t Type; \
    };
```

Does this improve the bitcode for you, without making it too x86-intrinsic-specific?

**Comment by pgoodman** [comment]
ping @tathanhdinh

**Comment by pgoodman** [comment]
Closing for now. In general we want to avoid admitting x86-specific intrinsics. Feasibly we could use the debug intrinsics library, which I have seen somewhere online, as a way of getting the goals of Remill (mostly architecture-neutral bitcode) while also benefitting from the work of others.
