### ISSUE TITLE
POPF/POPFD/POPFQ implementation hinders llvm optimization

### ISSUE THREAD

**Issue by pgarba** [lifting-bits/remill#326]
Hi,

The current implementation of POPF(D/Q) hinders the llvm optimizer to do its work.

PUSHF(Q) is pushing the rflag.flat on the stack.

```
DEF_SEM(DoPUSHFQ) {  
  SerializeFlags(state);  
  PushToStack<uint64_t>(memory, state, state.rflag.flat);  
  return memory;  
}

```
But POPF(Q) is restoring the aflag.

```
DEF_SEM(DoPOPFQ) {
  Flags f;
  f.flat = PopFromStack<uint64_t>(memory, state);
  state.aflag.af = f.af;
  state.aflag.cf = f.cf;
  state.aflag.df = f.df;
  state.aflag.of = f.of;
  state.aflag.pf = f.pf;
  state.aflag.sf = f.sf;
  state.aflag.zf = f.zf;

  state.rflag.id = f.id;

//  state.rflag.ac = f.ac;
//  state.rflag.tf = f.tf;
//  state.rflag.nt = f.nt;
  return memory;
}
```

The optimizer is not able to detect this and does not optimize the code around it.

A simple fix is to restore the rflag.flat like this:

`  state.rflag.flat = PopFromStack<uint64_t>(memory, state);`

A simple test case (48C7C428FF5C009C8b04249D):

```
00007FFC4E24FF80 | 48:C7C4 28FF5C00 | mov rsp,5CFF28 |  
00007FFC4E24FF87 | 9C | pushfq |  
00007FFC4E24FF88 | 8B0424 | mov eax,dword ptr ss:[rsp] |  
00007FFC4E24FF8B | 9D | popfq |  
```

out_norm.txt contains the current implementation.
out_ok.txt contains the new implementation.

Peter

[out_ok.txt](https://github.com/trailofbits/remill/files/2804682/out_ok.txt)
[out_norm.txt](https://github.com/trailofbits/remill/files/2804683/out_norm.txt)

**Comment by tathanhdinh** [comment]
Correct me if I'm wrong, it seems that `remill` "mostly" uses `aflag` for ring3 instructions, and `rflag` used "mostly" with ring0 instructions. 

https://github.com/trailofbits/remill/blob/e41c0a5a2716c9fbcdf9fc1a4f0c548835809605/remill/Arch/X86/Runtime/State.h#L723-L726

I still don't understand this decision, maybe this helps LLVM optimizes operations on flags: bit operations are changed to byte operations.

For the case of `pushfq` and `popfq`, I'm not sure that one neutralizes the other. For example `pushfq` clears VM and RF bits before saving, while `popfq` has no effect on F, IOPL, VIP, VIF, VM bits.

These stack operations are complicated, though.

**Comment by pgarba** [comment]
The quick fix I did is wrong. I'm currently working on a accurate fix for this problem which keeps the current remill logic of `aflag` and `rflag` as it as and also lets the llvm optimizer apply better optimizations.

**Comment by pgoodman** [comment]
Closing this issue for now.
