### ISSUE TITLE
Support debian stretch

### ISSUE THREAD

**Issue by jberryman** [lifting-bits/remill#329]
I'm following the McSema install instructions. Received: 

```
(mcsema-ve) $ ./remill/scripts/build.sh --prefix /home/me/.local
[+] New install directory is /home/me/.local
[x] debian is not yet a supported distribution.
[x] Build aborted.
```

I modified `build.sh` to point to the (AFAICT) corresponding ubuntu version (see e.g. https://askubuntu.com/questions/445487/what-debian-version-are-the-different-ubuntu-versions-based-on/445496) of `OS_VERSION=ubuntu1604`, and the build seems to have worked.

Unfortunately I can't test other debian distros, but it might be worth making cases for them in the same way.

I can try to make a PR later, once I finish installing McSema and verify

**Comment by pgoodman** [comment]
@jberryman Please submit a PR if it works :-D

**Comment by pgoodman** [comment]
Closing.
