### ISSUE TITLE
rflag cleanup to allow better EFLAG optimizations

### ISSUE THREAD

**Issue by pgarba** [lifting-bits/remill#344]
[0001-This-patch-allows-the-llvm-optimizer-to-better-optim.zip](https://github.com/trailofbits/remill/files/3020321/0001-This-patch-allows-the-llvm-optimizer-to-better-optim.zip)

**Comment by pgoodman** [comment]
For now I'm not going to accept this into Remill, as the scope of these changes results in semantics that are slightly less accurate. In the case of McSema, these are overall good changes to have, though I suspect we could effect the same outcome if we injected in stores to the rflags field to "kill" them at key places, which is a direction where we're headed anyway.
