### ISSUE TITLE
Missing floating point instructions RSQRTSS and UNPCKHPS

### ISSUE THREAD

**Issue by lfrazer** [lifting-bits/remill#351]
See log output indicating missing instructions (logs are from running McSema on large x64 game binary):

E0615 16:25:29.556859 15732 Lifter.cpp:123] Missing semantics for instruction (AMD64 140b7f0c9 4 (BYTES f3 0f 52 dd) RSQRTSS_XMMss_XMMss (WRITE_OP (REG_128 XMM3)) (READ_OP (REG_128 XMM5)))

E0615 16:25:29.223357 15732 Lifter.cpp:123] Missing semantics for instruction (AMD64 140b7f7b0 3 (BYTES 0f 15 c2) UNPCKHPS_XMMps_XMMdq (WRITE_OP (REG_128 XMM0)) (READ_OP (REG_128 XMM0)) (READ_OP (REG_128 XMM2)))

**Comment by pgoodman** [comment]
This is fixed in #457.
