### ISSUE TITLE
Gcc compilation error

### ISSUE THREAD

**Issue by Aiethel** [lifting-bits/remill#357]
Using option `use-host-compiler` and setting `CXX` to `gcc-8.3` project cannot be built, since compiler complains about unknown option: `-Wgnu-alignof-expression`

Removing this from `cmake/settings.cmake` helps and build ends successfully. Is it safe to simply remove?

**Comment by pgoodman** [comment]
I have recently removed `--use-host-compiler`, with the goal of always using the host compiler. We'll be switching to vcpkg eventually and that should remove any leftover problems.
