### ISSUE TITLE
Build Issue on macOS Catalina Version 10.15.1

### ISSUE THREAD

**Issue by aaronyoo** [lifting-bits/remill#388]
Encountered an issue when building remill according to [these instructions](https://gist.github.com/pgoodman/0882459dc2ecff0e674b79815e9301ff). Symptom and workaround listed below.

Clang 9.0.0 in the TRAILOFBITS_LIBRARIES directory has a hard time finding 'algorithm' (see below)
```
#include <...> search starts here:
 /Users/aaronyoo/Repos/remill-src/remill
 /Users/aaronyoo/Repos/trailofbits/libraries/llvm/lib/clang/9.0.0/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)
End of search list.
/Users/aaronyoo/Repos/remill-src/remill/remill/Arch/X86/Runtime/BasicBlock.cpp:17:10: fatal error: 'algorithm' file not found
#include <algorithm>
```

Through diff testing with the apple installed version of clang++ in /usr/bin/clang++ (version 11), I found the culprit to be `/Library/Developer/CommandLineTools/usr/include/c++/v1`. The clang installed from source was not looking here. The workaround is using CPATH:

```
export CPATH=/Library/Developer/CommandLineTools/usr/include/c++/v1
```

More details about why this is happening: [https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojave](https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojave)

**Comment by artemdinaburg** [comment]
Closing since I believe the new instructions should work for MacOS builds
