### ISSUE TITLE
[Question] LLVM disassembler

### ISSUE THREAD

**Issue by romainthomas** [lifting-bits/remill#403]
Hello,
I was wondering why you don't use the LLVM framework [1][2][3] to disassemble the instructions ?
Is it because the disassemble is not as accurate as xed ? 

Thank you anyway for this project! 

[1] https://llvm.org/doxygen/classllvm_1_1MCDisassembler.html
[2] https://llvm.org/doxygen/classllvm_1_1MCInst.html
[3] https://llvm.org/doxygen/classllvm_1_1MCInstrDesc.html

**Comment by pgoodman** [comment]
Basically yes. And we'd like to arrange things in a way that is convenient for us. In the case of XED, the operand action information (read/write) helps this. For other decoders, we generally do it on a case-by-case for format-by-format basis.
