### ISSUE TITLE
'stddef.h' file not found (remill-clang-4.0)

### ISSUE THREAD

**Issue by dbwodlf3** [lifting-bits/remill#406]
hi.
i am trying some file to binary and lifting it to llvm ir.

```
//hello.c
#include <stdio.h>

int main(){
    printf("Hello World!\n");
    return 0;
}
```

```
$ remill-clang-4.0 hello.c
/usr/include/stdio.h:33:10: fatal error: 'stddef.h' file not found
```

thank you.

**Comment by dbwodlf3** [comment]
#336

**Comment by pgoodman** [comment]
Are you on macOS?

**Comment by dbwodlf3** [comment]
no. linux 18.04 on docker tool box on windiws10

**Comment by artemdinaburg** [comment]
These should work on latest docker builds

**Comment by dbwodlf3** [comment]
it is still not solved...!
i think reason of this problem is just installed only binary file with no env files(like include header files)
remill-clang-9.0 is same clang-9?
or there is a something special?
