### ISSUE TITLE
when build, z3 path

### ISSUE THREAD

**Issue by dbwodlf3** [lifting-bits/remill#419]
```
./scripts/build.sh
```

```
make[2]: *** No rule to make target '/opt/trailofbits/libraries/z3/lib/libz3.a', needed by 'tools/lift/remill-lift-9.0'.  Stop.
```
but other dependencies are found from ./remill-build/libraries\

https://github.com/lifting-bits/remill/blob/master/scripts/build.sh#L102

if delete add_subdirectory(tools) then it works. in remill/CMakeListes.txt

i think it is not wrong of remill. just cxx common repository's problem...

remill-build > tools > lift > CMakeFiles > remill-lift-9.0.dir > build.make

![image](https://user-images.githubusercontent.com/22485292/82547201-4d25a800-9b94-11ea-921e-be0eb6b17e04.png)

i wolud like to fix it but i don't know cxx repository how to make make files...

**Comment by artemdinaburg** [comment]
I was able to reproduce your issue. It looks like a new problem based on statically linking to Z3 instead of dynamically linking. 

For a workaround, try this:
```
cd <remill clone directory>/remill-build
mkdir -p /opt/trailofbits
cp -R libraries /opt/trailofbits/
```

**Comment by artemdinaburg** [comment]
Working on fixing this in cxx-common and remill; will take a bit for all changes to propagate through but the workaround above should work for you immediately.

**Comment by dbwodlf3** [comment]
but what you said doesn't work .
anyway, thank you ^^!

**Comment by artemdinaburg** [comment]
You got me between fixes :). Working on a more complete solution right now.
