### ISSUE TITLE
what means, add_custom_target(semantics)? in CMakeLists.txt

### ISSUE THREAD

**Issue by dbwodlf3** [lifting-bits/remill#421]
hi! 
as always, thank you for your help.

i read build.sh and CMakelists.txt and i found it
https://github.com/lifting-bits/remill/blob/master/CMakeLists.txt#L347

what it means?
it is to make semantic tables for AMD64 or AARCH64?
but. just. add_custom_target(name) and that is all. it doesn't do anythings.

https://github.com/lifting-bits/remill/blob/master/cmake/remillConfig.cmake.in#L34

and. why do like that?
add_custom_target(semantics)

**Comment by artemdinaburg** [comment]
Hi,

This sounds like its a better fit for discussion in our Slack channel. Someone may be able to better explain it to you in the #binary-lifting channel of the [Empire Hacking Slack](https://empireslacking.herokuapp.com/).
