### ISSUE TITLE
PABS/PAVG family fails on QEMU

### ISSUE THREAD

**Issue by RobertHenry6bev** [lifting-bits/remill#423]
The PABS/PAVG family is failing on QEMU when I run the test ./run-amd64-tests. I  believe QEMU is implementing SSE and SSE2

There's some code smell, but I could be looking in the wrong place.

The generated file remill-build/tests/X86/tests_amd64.S contains many functions like PABSWv128m128_2_lifted but, AFAICT, none of those functions contain instructions pabs or pavg. Looking at the PABSWv128m128_2_lifted there's (eventually) a lot of code involving pinsrw/punpcklwd/punpckldq/psllq that I can't figure out, but there's no pabs.

The templated (I presume) in remill/tests/X86/MMX/MISC.S all look entire plausible, invoking the appropriate instruction+operands.

**Comment by pgoodman** [comment]
One thing to keep in mind and that isn't stated in too many places is that Remill tries to model SSE/AVX vectors as arrays, instead of modelling them as vectors (e.g. with `__attribute__((vector_size(..)))`. This is so that the bitcode produced generally will use only "simple" versions of instructions, and so that a user can feasibly opt-in to vectorization using something like LLVM's auto-vectorization optimizations.

**Comment by artemdinaburg** [comment]
Looking into this a bit more; right now looking like it might be a bug in Remill semantics, but still investigating.

**Comment by artemdinaburg** [comment]
@RobertHenry6bev do you have some inputs/outputs for PABS family failing? I have been reviewing the code in remill and it looks correct, but I'd like to manually confirm some failing outputs to see if it is us or QEMU that is wrong.

As for PAVG family, there may have been an issue with some of our semantics, going to see if an update still passes our semantics tests, and if so, to see if it then runs in QEMU.

**Comment by RobertHenry6bev** [comment]
All I did was to run remill application on ubuntu 20.04 on QEMU/tcg
emulating an x86_64.  I spent a little time looking at the assembly code
that gdb led me to believe was running, but didn't look much beyond that.

I will swap this task back in and spent a little more time with trying to
get you data.

**Comment by artemdinaburg** [comment]
Thanks Robert! I'll try to replicate this as well using qemu-user to see if the same issue comes up.

**Comment by RobertHenry6bev** [comment]
At this point I've figured out how to narrow down the scope of the tests,
and learned what happens when I inject various deliberate faults.  I'm just
looking at PAVGB which gets lifted out and inlined to a large straight line
piece of code that does more or less normal basic instructions, nothing
fancy, doing what I'd expect in each uint8_t lane, namely (a+b+1)>>1.  So
at this time I would guess the problem is most likely in QEMU/tcg.  I have
only tried qemu system mode, not qemu user mode.

**Comment by RobertHenry6bev** [comment]
The non-llifted instance of pavgb %mm1, %mm2 SSE instruction under test is dynamically followed by a jmpq, then by an fxsave64 instruction. As far as I can tell, the implementation of pavgb in QEMU (eg, the runner for the non-lifted instance in remill) is receiving the right values in its operands, and computes the right value.  Beyond that, my head starts to spin. gdb doesn't report SSE %mm registers, and the data structure for the fxsave64 is complex and legacy dependent. Since many non-lifted "P" instructions are failing, at this point I suspect they are all SSE insns, and so hypothesize that the common mode of failure is the qemu implementation of fxsave64 or the assumptions about the use of fxsave64 in remill.

**Comment by RobertHenry6bev** [comment]
A small standalone program (attached) which has pavgb followed by fxsave64 runs fine under QEMU. I think the same sequence in remill correctly runs fxsave64, in that I see the desired value in the right place in memory after  fxsave64.  Setting a hardware watchpoint in  gdb (on qemu/tcg) results in a linux kernel fault, so I can't use that to catch memory overwrites to the block written by fxsave64.  valgrind also has issues running remill because of the explicit stack swaps.

Does remill do anything different based on probes of the cpuid? Perhaps qemu/tcg sets cpuid a little differently than bare metal.
[fxsave64.txt](https://github.com/lifting-bits/remill/files/4697783/fxsave64.txt)

**Comment by RobertHenry6bev** [comment]
The failing instructions such as "PAVGB" are all legacy SSE instructions. They are saved with fxsave64 instruction, following the layout of https://www.felixcloutier.com/x86/fxsave#tbl-3-44 Remill seems to import these saved values and stuffs them into yet another data structure for later comparison of native vs lifted. The import is done in function ImportX87X86State https://github.com/lifting-bits/remill/blob/a466b430eab3554e68db9d0b1cc5bbb0b9926a83/tests/X86/Run.cpp#L520 which checks the bits 64..79 of a saved X87[sic] register.  Line 520 assumes in Run.cpp assumes that these 16 bits are all 1s aka infinity. 

However... These 16 bits are reserved. Intel table 3-44 says "When the MMX technology registers are saved, the high 16 bits of the field are reserved."

It seems that hardware puts all 1's in these bits, but QEMU does something else.  Hence, remill works on hardware, but fails on QEMU.

**Comment by RobertHenry6bev** [comment]
https://xem.github.io/minix86/manual/intel-x86-and-64-manual-vol1/o_7281d5ea06a5b67a-233.html states that mmx instructions write all 1's to the exponent part of the fp80.  So it looks like the assumptions in remill are OK, and qemu is non-compliant.

**Comment by pgoodman** [comment]
@RobertHenry6bev Closing this for now, unless you think there are other issues related to these two instructions.

Next up, I recommend looking at floating point fused multiply and add. I believe we aren't handling it correctly, though we had a branch or an issue with a correct solution. A correct solution requires infinite precision. It's possible that QEMU is also doing the incorrect thing.

**Comment by pgoodman** [comment]
See #168 for reference.
