### ISSUE TITLE
Any plan to do a recent release? 

### ISSUE THREAD

**Issue by Yikun** [lifting-bits/remill#432]
Hi, team.

We could only see latest version was released at 5 Dec 2017 (v2.0.0) [1]. And looks like we only provide docker dev platform, and do the daily build on docker hub [2].

Do we have plan to do the latest release recently? or to say if we plan to do some intergration with `remill`, what's the recommended version?

Note that our team have some limitations on the choose of open source software, that means we can only choose the stable version, that means we will miss some wanderful feature and fixes in recent commits.

[1] https://github.com/lifting-bits/remill/releases
[2] https://hub.docker.com/r/trailofbits/remill

**Comment by artemdinaburg** [comment]
Hi Yikun,

We were actually thinking about doing a rolling (but still versioned) release schedule like we do for [cxx-common](https://github.com/trailofbits/cxx-common/releases). 

Would that work for your situation? If yes I can try to prioritize setting that up.

**Comment by Yikun** [comment]
@artemdinaburg Yes, I think it meets our requirements.

In addition, it would be good if we could see aarch64 version in release list, and we are using centos series OS, so if we could see more multi-arch and multi-OS support on release.

**Comment by Yikun** [comment]
@artemdinaburg Any progress on this? Would you mind to set up a release for remill?

**Comment by artemdinaburg** [comment]
This is still a TODO, I have been busy with other work things and have not had time to set this up.

**Comment by pgoodman** [comment]
Remill's master branch is now already up-to-date with what would be the next release. We'll probably cut the release when we bring McSema up-to-date with Remill master. We've got some tests failing there that @kumarak is working through.

**Comment by artemdinaburg** [comment]
This is now done
