### ISSUE TITLE
ARMv7-A Support

### ISSUE THREAD

**Issue by artemdinaburg** [lifting-bits/remill#443]
We are going to need ARMv7-A support, initially user-space only.

Making this issue to track ARMv7-A support progress.

**Comment by pgoodman** [comment]
We should try to auto-generate a decoder from the spec, but not in such a dumb way as I did it for aarch64.  That is, the aarch64 decoder ignores the fact that there are a limited number of encoded forms and yolos it. We should change it to break things down by which encoding form to use.

**Comment by artemdinaburg** [comment]
I know ARMv8 has machine readable specs, does ARMv7-A have the same ones? I am all for the idea though, whether its machine readable spec or parsed out of a manual, etc.

**Comment by woachk** [comment]
The AArch32 machine-readable specification is available at: https://developer.arm.com/-/media/developer/products/architecture/armv8-a-architecture/AArch32_v82A_ISA_xml_00bet3.1.tar.gz for example (for v8.2-A)

**Comment by pgoodman** [comment]
We're following the spec, though making a decoder/lifter for Remill is a bit more subtle than simply "using the spec." The key issue is that one must look at the instruction format, at the executable semantics, and then make a decision about what aspects should and can go into the decoder, and what aspects should go into Remill's version of the semantics.
