### ISSUE TITLE
llvm nagging about failure of loop unrolling

### ISSUE THREAD

**Issue by DCNick3** [lifting-bits/remill#452]
Whenever I run `remill-lift` (even as simple as `remill-lift-10.0 --bytes c3 --arch x86 --ir_out /dev/stdout`), I get a bunch of repeating warnings from clang: 

```
warning: <unknown>:0:0: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
```

It's not clear for me does it refer to (are there loop in semantics definitions?) and the produced bitcode seems to be fine, but I'm not sure if this is a real problem or just some weird unrelated message. Can you please look into it?

**Comment by pgoodman** [comment]
In the semantics, we have a bunch of `_Pragma("unroll")` directives, and Clang is refusing to follow them. These aren't actual problems, though.

**Comment by DCNick3** [comment]
Nice. Will have to silence those warnings I guess
