### ISSUE TITLE
Infinite recursion in the semantics

### ISSUE THREAD

**Issue by DCNick3** [lifting-bits/remill#504]
It seems that the implementation of the FCOMP (and FUCOMP) with memory argument results in an infinite recursion:

```
template <typename S2>
DEF_FPU_SEM(FUCOMPmem, RF80 src1, S2 src2) {
  SetFPUDp(src2);
  return FUCOMPmem(memory, state, src1, src2, pc, fop);
}

template <typename S2>
DEF_FPU_SEM(FCOMPmem, RF80 src1, S2 src2) {
  SetFPUDp(src2);
  return FCOMPmem(memory, state, src1, src2, pc, fop);
}
```

Probably some other function should have been called...

**Comment by pgoodman** [comment]
@DCNick3 good find! Can you submit a PR that calls whatever was meant to be called?

**Comment by DCNick3** [comment]
I think if I will poke around I will find which one is meant to be called and submit a PR
