### ISSUE TITLE
Build fail on Ubuntu 22.04, ARMv8

### ISSUE THREAD

**Issue by aqjune** [lifting-bits/remill#641]
Hi all,

While following through the installation guide using `build.sh`, I am seeing this error:

```
ubuntu@ip-172-31-10-5:~$ ./remill/scripts/build.sh
[x] Ubuntu jammy is not supported. Only xenial (16.04) and trusty (14.04) are supported.
[-] Library version is vcpkg__llvm-15_arm64
~/lifting-bits-downloads ~/remill-build
Fetching: https://github.com/lifting-bits/cxx-common/releases/download/v0.2.12/vcpkg__llvm-15_arm64.tar.xz and placing in /home/ubuntu/lifting-bits-downloads
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0    116      0 --:--:-- --:--:-- --:--:--   118
+ tar -xJf vcpkg__llvm-15_arm64.tar.xz --warning=no-timestamp
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
[x] Unable to download vcpkg libraries build vcpkg__llvm-15_arm64.
[x] Build aborted.
```

Does anyone have any idea about this?

**Comment by ekilmer** [comment]
Hello! There are a few things going on here...

First, the error message about only supporting `xenial (16.04) and trusty (14.04)` is wrong. We only translate for Ubuntu 20.04, so your distribution, 22.04, is not supported yet by the build script.

Second, our pre-built releases do not support ARM64 anymore. I have [opened an issue](https://github.com/lifting-bits/cxx-common/issues/995) to track support for this (through cross-compilation) on GitHub Actions.

To work around these issues, you will need to build cxx-common on your machine. Follow the directions [here](https://github.com/lifting-bits/cxx-common#building-from-source). Note, you will probably want to pass `--release` to the `build_dependencies.sh` script to get similar binaries to what is in cxx-common releases; this will build Release build type only. If you do not pass `--release`, then you will build a Debug version of LLVM, which can take 100GB+ of disk space.

**Comment by aqjune** [comment]
I see, thank you for a reply! Maybe I can try remill on my x86-64 EC2 instance instead.
